# Generated by Django 4.2.11 on 2024-04-05 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_cart"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={},
        ),
        migrations.RemoveIndex(
            model_name="product",
            name="shop_produc_name_a2070e_idx",
        ),
        migrations.RemoveIndex(
            model_name="product",
            name="shop_produc_created_ef211c_idx",
        ),
    ]
