# Generated by Django 4.2.11 on 2024-04-06 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0006_order"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cartitem",
            name="cart",
        ),
        migrations.RemoveField(
            model_name="cartitem",
            name="product",
        ),
        migrations.RemoveField(
            model_name="order",
            name="cart",
        ),
        migrations.DeleteModel(
            name="Cart",
        ),
        migrations.DeleteModel(
            name="CartItem",
        ),
        migrations.DeleteModel(
            name="Order",
        ),
    ]
