# Generated by Django 4.2.11 on 2024-04-06 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0008_cart_order_cartitem"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cart",
            name="status",
        ),
    ]
