# Generated by Django 5.0 on 2024-04-07 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0013_remove_order_cart_order_address_order_city"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[("PENDING", "pending"), ("PAID", "Paid")],
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
