# Generated by Django 5.0 on 2024-04-09 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0014_alter_order_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="invoice",
            field=models.TextField(null=True),
        ),
    ]
